FROM docker.io/debian:bookworm-slim

ARG LOCAL_USER=macwawrz
ENV LOCAL_USER=${LOCAL_USER}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y openssh-server tini -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd ${LOCAL_USER} && \
    mkdir /run/sshd && \
    chmod 755 /run/sshd

COPY entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

EXPOSE 22

ENTRYPOINT ["/usr/bin/tini", "--", "/entrypoint.sh"]
CMD ["/usr/sbin/sshd", "-Dde"]
